version: '3'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - '5000:5000'
      - '15000:9229'
    environment:
      PORT: 5000
      DATABASE_URL: mongo_URL
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - tictactoe
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - '3000:3000'
      - '13000:9229'
    environment:
      API_URL: http://localhost:5000/api
    volumes:
      - ./packages/frontend:/usr/src/app/packages/frontend
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - tictactoe
    restart: unless-stopped

networks:
  tictactoe:
    driver: bridge
